<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE design [
  <!ELEMENT design (name,description,generated,cmsversion,template+,stylesheet*,file*)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT description (#PCDATA)>
  <!ELEMENT generated (#PCDATA)>
  <!ELEMENT cmsversion (#PCDATA)>
  <!ELEMENT template (tkey,tname,tdesc,tdata,ttype_originator,ttype_name)>
  <!ELEMENT tkey (#PCDATA)>
  <!ELEMENT tname (#PCDATA)>
  <!ELEMENT tdesc (#PCDATA)>
  <!ELEMENT tdata (#PCDATA)>
  <!ELEMENT ttype_originator (#PCDATA)>
  <!ELEMENT ttype_name (#PCDATA)>
  <!ELEMENT stylesheet (csskey,cssname,cssdesc,cssmediatype,cssmediaquery,cssdata)>
  <!ELEMENT csskey (#PCDATA)>
  <!ELEMENT cssname (#PCDATA)>
  <!ELEMENT cssdesc (#PCDATA)>
  <!ELEMENT cssmediatype (#PCDATA)>
  <!ELEMENT cssmediaquery (#PCDATA)>
  <!ELEMENT cssdata (#PCDATA)>
  <!ELEMENT file (fkey,fvalue,fdata?)>
  <!ELEMENT fkey (#PCDATA)>
  <!ELEMENT fvalue (#PCDATA)>
  <!ELEMENT fdata (#PCDATA)>
]>
<design>
  <name>BootstrapBase</name>
  <description><![CDATA[UGxhaW4gYm9vdHN0cmFwIGRlc2lnbg==]]></description>
  <generated><![CDATA[MTUwMjI5OTk3OA==]]></generated>
  <cmsversion><![CDATA[Mi4xLjY=]]></cmsversion>
  <template>
    <tkey>__TPL,,a2fe81218eb6b4afc796b711f60d457c__</tkey>
    <tname><![CDATA[Ym9vdHN0cmFwLW1lbnVpbnZlcnNl]]></tname>
    <tdesc><![CDATA[]]></tdesc>
    <tdata><![CDATA[PGRpdiBjbGFzcz0iY29udGFpbmVyLWZsdWlkIj4NCiAgICA8ZGl2IGNsYXNzPSJuYXZiYXItaGVhZGVyIj4NCiAgICAgIDxidXR0b24gdHlwZT0iYnV0dG9uIiBjbGFzcz0ibmF2YmFyLXRvZ2dsZSIgZGF0YS10b2dnbGU9ImNvbGxhcHNlIiBkYXRhLXRhcmdldD0iI215TmF2YmFyIj4NCiAgICAgICAgICA8c3BhbiBjbGFzcz0iaWNvbi1iYXIiPjwvc3Bhbj4NCiAgICAgICAgICA8c3BhbiBjbGFzcz0iaWNvbi1iYXIiPjwvc3Bhbj4NCiAgICAgICAgICA8c3BhbiBjbGFzcz0iaWNvbi1iYXIiPjwvc3Bhbj4NCiAgICAgIDwvYnV0dG9uPg0KICAgICAgPGEgY2xhc3M9Im5hdmJhci1icmFuZCIgaHJlZj0iIyI+PC9hPg0KICAgIDwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImNvbGxhcHNlIG5hdmJhci1jb2xsYXBzZSIgaWQ9Im15TmF2YmFyIj4NCiAgICAgIDx1bCBjbGFzcz0ibmF2IG5hdmJhci1uYXYiPg0KICAgICAgICB7aWYgJGNvdW50ID4gMH0NCiAgICAgICAgICAgIHtmb3JlYWNoIGZyb209JG5vZGVsaXN0IGl0ZW09bm9kZX0NCiAgICAgICAgICAgICAgICB7aWYgJG5vZGUtPmRlcHRoID4gJG5vZGUtPnByZXZkZXB0aH0NCiAgICAgICAgICAgICAgICAgICAge3JlcGVhdCBzdHJpbmc9Ijx1bCBjbGFzcz0nZHJvcGRvd24tbWVudSc+IiB0aW1lcz0kbm9kZS0+ZGVwdGgtJG5vZGUtPnByZXZkZXB0aH0NCiAgICAgICAgICAgICAgICB7ZWxzZWlmICRub2RlLT5kZXB0aCA8ICRub2RlLT5wcmV2ZGVwdGh9DQogICAgICAgICAgICAgICAgICAgIHtyZXBlYXQgc3RyaW5nPSI8L2xpPjwvdWw+IiB0aW1lcz0kbm9kZS0+cHJldmRlcHRoLSRub2RlLT5kZXB0aH0NCiAgICAgICAgICAgICAgICAgICAgPC9saT4NCiAgICAgICAgICAgICAgICB7ZWxzZWlmICRub2RlLT5pbmRleCA+IDB9DQogICAgICAgICAgICAgICAgICAgIDwvbGk+DQogICAgICAgICAgICAgICAgey9pZn0NCiAgICAgICAgICAgICAgICB7aWYgJG5vZGUtPmNoaWxkcmVuX2V4aXN0ICYmICRub2RlLT5oaWVyYXJjaHl8c3Ryc3RyOiIuIn0NCiAgICAgICAgICAgICAgICAgICAgPGxpIGNsYXNzPSJkcm9wZG93bi1zdWJtZW51Ij4NCiAgICAgICAgICAgICAgICAgICAgICAgIDxhIGNsYXNzPSJkcm9wZG93bi10b2dnbGUiIGRhdGEtdG9nZ2xlPSJkcm9wZG93biIgaHJlZj0ieyRub2RlLT51cmx9IntpZiAkbm9kZS0+dGFyZ2V0IG5lICIifSB0YXJnZXQ9Inskbm9kZS0+dGFyZ2V0fSJ7L2lmfT4geyRub2RlLT5tZW51dGV4dH08L2E+DQogICAgICAgICAgICAgICAge2Vsc2VpZiAkbm9kZS0+Y2hpbGRyZW5fZXhpc3R9DQogICAgICAgICAgICAgICAgICAgIDxsaSBjbGFzcz0iZHJvcGRvd24iPg0KICAgICAgICAgICAgICAgICAgICAgICAgPGEgY2xhc3M9ImRyb3Bkb3duLXRvZ2dsZSIgZGF0YS10b2dnbGU9ImRyb3Bkb3duIiBocmVmPSJ7JG5vZGUtPnVybH0ie2lmICRub2RlLT50YXJnZXQgbmUgIiJ9IHRhcmdldD0ieyRub2RlLT50YXJnZXR9InsvaWZ9PiB7JG5vZGUtPm1lbnV0ZXh0fSA8c3BhbiBjbGFzcz0iY2FyZXQiLz48L2E+DQogICAgICAgICAgICAgICAge2Vsc2V9DQogICAgICAgICAgICAgICAgICAgIDxsaT48YSBocmVmPSJ7JG5vZGUtPnVybH0ie2lmICRub2RlLT50YXJnZXQgbmUgIiJ9IHRhcmdldD0ieyRub2RlLT50YXJnZXR9InsvaWZ9PiB7JG5vZGUtPm1lbnV0ZXh0fSA8L2E+DQogICAgICAgICAgICAgICAgey9pZn0NCiAgICAgICAgICAgIA0KICAgICAgICAgICAgey9mb3JlYWNofQ0KICAgICAgICAgICAgDQogICAgICAgICAgICB7cmVwZWF0IHN0cmluZz0iPC9saT48L3VsPiIgdGltZXM9JG5vZGUtPmRlcHRoLTF9PC9saT4NCiAgICAgICAgey9pZn0NCiAgICAgIDwvdWw+DQogICAgICA8dWwgY2xhc3M9Im5hdiBuYXZiYXItbmF2IG5hdmJhci1yaWdodCI+DQogICAgICAgICAgICA8bGk+e2JzX2xpbmtfc3RhdGljXzF9PC9saT4NCiAgICAgICAgICAgIDxsaT57YnNfbGlua19zdGF0aWNfMn08L2xpPg0KICAgICAgICAgICAgPGxpPntic19saW5rX3N0YXRpY18zfTwvbGk+DQogICAgICA8L3VsPg0KICAgIDwvZGl2Pg0KPC9kaXY+]]></tdata>
    <ttype_originator><![CDATA[TWVudU1hbmFnZXI=]]></ttype_originator>
    <ttype_name><![CDATA[bmF2aWdhdGlvbg==]]></ttype_name>
  </template>
  <template>
    <tkey>__TPL,,ca4c50b905dc21ea17a10549a6f5944f__</tkey>
    <tname><![CDATA[Ym9vdHN0cmFw]]></tname>
    <tdesc><![CDATA[]]></tdesc>
    <tdata><![CDATA[e3Byb2Nlc3NfcGFnZWRhdGF9DQo8IURPQ1RZUEUgaHRtbD4NCjxodG1sPg0KPGhlYWQ+DQogICAgPG1ldGEgY2hhcnNldD0idXRmLTgiPg0KICAgIDxtZXRhIGh0dHAtZXF1aXY9IlgtVUEtQ29tcGF0aWJsZSIgY29udGVudD0iSUU9ZWRnZSI+DQogICAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCwgaW5pdGlhbC1zY2FsZT0xIj4NCiAgICA8IS0tIFRoZSBhYm92ZSAzIG1ldGEgdGFncyAqbXVzdCogY29tZSBmaXJzdCBpbiB0aGUgaGVhZDsgYW55IG90aGVyIGhlYWQgY29udGVudCBtdXN0IGNvbWUgKmFmdGVyKiB0aGVzZSB0YWdzIC0tPg0KICAgIDx0aXRsZT57c2l0ZW5hbWV9IC0ge3RpdGxlfTwvdGl0bGU+DQogICAgPGxpbmsgcmVsPSJhbHRlcm5hdGUiIHR5cGU9ImFwcGxpY2F0aW9uL3Jzcyt4bWwiIHRpdGxlPSJ7c2l0ZW5hbWV9IFJTUyBGZWVkIiBocmVmPSJ7YnNfcnNzX3VybH0iIC8+DQoNCiAgICA8IS0tIEJvb3RzdHJhcCAtLT4NCiAgICA8bGluayAgaHJlZj0iX19VUkwsLGE3Njk4MTY5NWE0M2NlNzliY2IxZTRjMWVkYjFiNjM4X18iIHJlbD0ic3R5bGVzaGVldCI+DQoNCiAgICA8IS0tIEhUTUw1IHNoaW0gYW5kIFJlc3BvbmQuanMgZm9yIElFOCBzdXBwb3J0IG9mIEhUTUw1IGVsZW1lbnRzIGFuZCBtZWRpYSBxdWVyaWVzIC0tPg0KICAgIDwhLS0gV0FSTklORzogUmVzcG9uZC5qcyBkb2Vzbid0IHdvcmsgaWYgeW91IHZpZXcgdGhlIHBhZ2UgdmlhIGZpbGU6Ly8gLS0+DQogICAgPCEtLVtpZiBsdCBJRSA5XT4NCiAgICAgIDxzY3JpcHQgc3JjPSJodHRwczovL29zcy5tYXhjZG4uY29tL2h0bWw1c2hpdi8zLjcuMy9odG1sNXNoaXYubWluLmpzIj48L3NjcmlwdD4NCiAgICAgIDxzY3JpcHQgc3JjPSJodHRwczovL29zcy5tYXhjZG4uY29tL3Jlc3BvbmQvMS40LjIvcmVzcG9uZC5taW4uanMiPjwvc2NyaXB0Pg0KICAgIDwhW2VuZGlmXS0tPg0KICAgIDxsaW5rIHJlbD0ic3R5bGVzaGVldCIgIGhyZWY9Il9fVVJMLCwwNDVmYjZhYzNjMDgyYjAxMTkxZTc0YjhjMTZjOTc3MF9fIj4NCg0KICAgIDxzdHlsZT4NCiAgICAgIC52Y2VudGVyIHsNCiAgICAgICAgICAgIGRpc3BsYXk6IGlubGluZS1ibG9jazsNCiAgICAgICAgICAgIHZlcnRpY2FsLWFsaWduOiBtaWRkbGU7DQogICAgICAgICAgICBmbG9hdDogbm9uZTsNCiAgICAgIH0NCiAgICAgIC5mb290ZXIgew0KICAgICAgICAgICAgYm90dG9tOiAwOw0KICAgICAgICAgICAgLyp3aWR0aDogMTAwJTsqLw0KICAgICAgICAgICAgaGVpZ2h0OiA5MHB4Ow0KICAgICAgICAgICAgbGluZS1oZWlnaHQ6IDYwcHg7DQogICAgICAgICAgICBiYWNrZ3JvdW5kLWNvbG9yOiAjZmZmZmZmOw0KICAgICAgICAgICAgYmFja2dyb3VuZC1pbWFnZTogdXJsKCd7YnNfaW1nX2Zvb3Rlcn0nKTsNCiAgICAgIH0NCiAgICAgIC5oaWdobGlnaHQgew0KICAgICAgICAgICAgcGFkZGluZzogOXB4IDE0cHg7DQogICAgICAgICAgICBtYXJnaW4tYm90dG9tOiAxNHB4Ow0KICAgICAgICAgICAgYmFja2dyb3VuZC1jb2xvcjogI2Y3ZjdmOTsNCiAgICAgICAgICAgIGJvcmRlcjogMXB4IHNvbGlkICNlMWUxZTg7DQogICAgICAgICAgICBib3JkZXItcmFkaXVzOiA0cHg7DQogICAgICB9DQogICAgLmRyb3Bkb3duLXN1Ym1lbnUgew0KICAgICAgICAgICAgcG9zaXRpb246IHJlbGF0aXZlOw0KICAgIH0NCiAgICANCiAgICAuZHJvcGRvd24tc3VibWVudT4uZHJvcGRvd24tbWVudSB7DQogICAgICAgICAgICB0b3A6IDA7DQogICAgICAgICAgICBsZWZ0OiAxMDAlOw0KICAgICAgICAgICAgbWFyZ2luLXRvcDogLTZweDsNCiAgICAgICAgICAgIG1hcmdpbi1sZWZ0OiAtMXB4Ow0KICAgICAgICAgICAgLXdlYmtpdC1ib3JkZXItcmFkaXVzOiAwIDZweCA2cHggNnB4Ow0KICAgICAgICAgICAgLW1vei1ib3JkZXItcmFkaXVzOiAwIDZweCA2cHg7DQogICAgICAgICAgICBib3JkZXItcmFkaXVzOiAwIDZweCA2cHggNnB4Ow0KICAgIH0NCiAgICANCiAgICAuZHJvcGRvd24tc3VibWVudTpob3Zlcj4uZHJvcGRvd24tbWVudSB7DQogICAgICAgICAgICBkaXNwbGF5OiBibG9jazsNCiAgICB9DQogICAgDQogICAgLmRyb3Bkb3duLXN1Ym1lbnU+YTphZnRlciB7DQogICAgICAgICAgICBkaXNwbGF5OiBibG9jazsNCiAgICAgICAgICAgIGNvbnRlbnQ6ICIgIjsNCiAgICAgICAgICAgIGZsb2F0OiByaWdodDsNCiAgICAgICAgICAgIHdpZHRoOiAwOw0KICAgICAgICAgICAgaGVpZ2h0OiAwOw0KICAgICAgICAgICAgYm9yZGVyLWNvbG9yOiB0cmFuc3BhcmVudDsNCiAgICAgICAgICAgIGJvcmRlci1zdHlsZTogc29saWQ7DQogICAgICAgICAgICBib3JkZXItd2lkdGg6IDVweCAwIDVweCA1cHg7DQogICAgICAgICAgICBib3JkZXItbGVmdC1jb2xvcjogI2NjYzsNCiAgICAgICAgICAgIG1hcmdpbi10b3A6IDVweDsNCiAgICAgICAgICAgIG1hcmdpbi1yaWdodDogLTEwcHg7DQogICAgfQ0KICAgIA0KICAgIC5kcm9wZG93bi1zdWJtZW51OmhvdmVyPmE6YWZ0ZXIgew0KICAgICAgICAgICAgYm9yZGVyLWxlZnQtY29sb3I6ICNmZmY7DQogICAgfQ0KICAgIA0KICAgIC5kcm9wZG93bi1zdWJtZW51LnB1bGwtbGVmdCB7DQogICAgICAgICAgICBmbG9hdDogbm9uZTsNCiAgICB9DQogICAgDQogICAgLmRyb3Bkb3duLXN1Ym1lbnUucHVsbC1sZWZ0Pi5kcm9wZG93bi1tZW51IHsNCiAgICAgICAgICAgIGxlZnQ6IC0xMDAlOw0KICAgICAgICAgICAgbWFyZ2luLWxlZnQ6IDEwcHg7DQogICAgICAgICAgICAtd2Via2l0LWJvcmRlci1yYWRpdXM6IDZweCAwIDZweCA2cHg7DQogICAgICAgICAgICAtbW96LWJvcmRlci1yYWRpdXM6IDZweCAwIDZweCA2cHg7DQogICAgICAgICAgICBib3JkZXItcmFkaXVzOiA2cHggMCA2cHggNnB4Ow0KICAgIH0NCg0KDQogICAgPC9zdHlsZT4NCiAgICB7U3RhdGlzdGljczJ9DQogICAge2Ntc19zdHlsZXNoZWV0fQ0KICAgIHttZXRhZGF0YX0NCiAgICB7Y21zX3NlbGZsaW5rIGRpcj0ic3RhcnQiIHJlbGxpbms9MX0NCiAgICB7Y21zX3NlbGZsaW5rIGRpcj0icHJldiIgcmVsbGluaz0xfQ0KICAgIHtjbXNfc2VsZmxpbmsgZGlyPSJuZXh0IiByZWxsaW5rPTF9DQo8L2hlYWQ+DQoNCjxib2R5Pg0KICAgIA0KICAgIDxkaXYgY2xhc3M9ImNvbnRhaW5lciI+DQogICAgICA8ZGl2IGNsYXNzPSJyb3ciPg0KICAgICAgICAgICAgPGRpdiBjbGFzcz0iY29sLXhzLTEgY29sLW1kLTIgY29sLWxnLTIgdmNlbnRlciI+DQogICAgICAgICAgICAgICAgICA8aW1nIGNsYXNzPSJpbWctcmVzcG9uc2l2ZSIgc3JjPSJ7YnNfaW1nX2xvZ299IiBhbHQ9IkxvZ28ge3NpdGVuYW1lfSIvPg0KICAgICAgICAgICAgPC9kaXY+PCEtLQ0KICAgICAgICAgICAgLS0+PGRpdiBjbGFzcz0iY29sLXhzLTEwIGNvbC1tZC0xMCBjb2wtbGctMTAgdmNlbnRlciI+DQogICAgICAgICAgICAgICAgICA8aDE+e3NpdGVuYW1lfTwvaDE+DQogICAgICAgICAgICA8L2Rpdj4NCiAgICAgIDwvZGl2Pg0KICAgICAgPGRpdj4NCiAgICAgICAgIDxuYXYgY2xhc3M9Im5hdmJhciBuYXZiYXItaW52ZXJzZSI+DQogICAgICAgICAgICB7bWVudSB0ZW1wbGF0ZT0iX19UUEwsLGEyZmU4MTIxOGViNmI0YWZjNzk2YjcxMWY2MGQ0NTdjX18ifQ0KICAgICAgICAgIDwvbmF2Pg0KICAgICAgPC9kaXY+DQogICAgICA8ZGl2IGNsYXNzPSJyb3ciPg0KICAgICAgICA8ZGl2IGNsYXNzPSJjb2wteHMtMTIgY29sLW1kLTEyIGNvbC1sZy0xMiI+DQogICAgICAgICAgICA8aDIgY2xhc3M9InRpdGxlIj57dGl0bGV9PC9oMj4NCiAgICAgICAgICAgIHtjb250ZW50fQ0KICAgICAgICA8L2Rpdj4NCiAgICAgIDwvZGl2Pg0KICAgICAgPGRpdiBjbGFzcz0icm93Ij4NCiAgICAgICAgICAgIDxkaXYgY2xhc3M9ImNvbC1tZC0xMiI+DQogICAgICAgICAgICAgICAgICA8ZGl2IGNsYXNzPSJmb290ZXIiPjwvZGl2Pg0KICAgICAgICAgICAgPC9kaXY+DQogICAgICA8L2Rpdj4NCiAgICA8L2Rpdj4NCg0KICAgIDwhLS0galF1ZXJ5IChuZWNlc3NhcnkgZm9yIEJvb3RzdHJhcCdzIEphdmFTY3JpcHQgcGx1Z2lucykgLS0+DQogICAgPHNjcmlwdCBzcmM9Imh0dHBzOi8vYWpheC5nb29nbGVhcGlzLmNvbS9hamF4L2xpYnMvanF1ZXJ5LzEuMTIuNC9qcXVlcnkubWluLmpzIj48L3NjcmlwdD4NCiAgICA8IS0tIEluY2x1ZGUgYWxsIGNvbXBpbGVkIHBsdWdpbnMgKGJlbG93KSwgb3IgaW5jbHVkZSBpbmRpdmlkdWFsIGZpbGVzIGFzIG5lZWRlZCAtLT4NCiAgICA8c2NyaXB0ICBzcmM9Il9fVVJMLCw2OWUxMzFjNGRiZWQwZjcxZWQ2ZGE4M2ViNDc0NTYwYl9fIj48L3NjcmlwdD4NCjwvYm9keT4NCjwvaHRtbD4=]]></tdata>
    <ttype_originator><![CDATA[X19DT1JFX18=]]></ttype_originator>
    <ttype_name><![CDATA[cGFnZQ==]]></ttype_name>
  </template>
</design>
